In [0]:
import pandas as pd
import numpy as np

In [0]:
ratings = open('ratings.dat', 'r').readlines()
users= open('users.dat', 'r').readlines()
movies= open('movies.dat', 'r',encoding="latin-1").readlines()

In [5]:
ratings[:5]

['1::1193::5::978300760\n',
 '1::661::3::978302109\n',
 '1::914::3::978301968\n',
 '1::3408::4::978300275\n',
 '1::2355::5::978824291\n']

In [6]:
users[:5]

['1::F::1::10::48067\n',
 '2::M::56::16::70072\n',
 '3::M::25::15::55117\n',
 '4::M::45::7::02460\n',
 '5::M::25::20::55455\n']

In [7]:
movies[:5]

["1::Toy Story (1995)::Animation|Children's|Comedy\n",
 "2::Jumanji (1995)::Adventure|Children's|Fantasy\n",
 '3::Grumpier Old Men (1995)::Comedy|Romance\n',
 '4::Waiting to Exhale (1995)::Comedy|Drama\n',
 '5::Father of the Bride Part II (1995)::Comedy\n']

In [0]:
ratings_list = [i.strip().split("::") for i in open('ratings.dat', 'r').readlines()]
users_list = [i.strip().split("::") for i in open('users.dat', 'r').readlines()]
movies_list = [i.strip().split("::") for i in open('movies.dat', 'r',encoding="latin-1").readlines()]

In [0]:
ratings = np.array(ratings_list)
users = np.array(users_list)
movies = np.array(movies_list)

In [0]:
ratings_df = pd.DataFrame(ratings_list, columns = ['UserID', 'MovieID', 'Rating', 'Timestamp'], dtype = int)
movies_df = pd.DataFrame(movies_list, columns = ['MovieID', 'Title', 'Genres'])
movies_df['MovieID'] = movies_df['MovieID'].apply(pd.to_numeric)

In [11]:
movies_df.head(5)

MovieID                               Title                        Genres
0        1                    Toy Story (1995)   Animation|Children's|Comedy
1        2                      Jumanji (1995)  Adventure|Children's|Fantasy
2        3             Grumpier Old Men (1995)                Comedy|Romance
3        4            Waiting to Exhale (1995)                  Comedy|Drama
4        5  Father of the Bride Part II (1995)                        Comedy

In [12]:

ratings_df.head(5)

UserID MovieID Rating  Timestamp
0      1    1193      5  978300760
1      1     661      3  978302109
2      1     914      3  978301968
3      1    3408      4  978300275
4      1    2355      5  978824291

In [16]:

R_df = ratings_df.pivot(index = 'UserID', columns ='MovieID', values = 'Rating').fillna(0)
R_df.head()
R_df.shape

(6040, 3706)

In [19]:

R=R_df.values
R



array([['5', 0, 0, ..., 0, 0, 0],
       ['5', 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       ['4', 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=object)

In [20]:
R=R.astype(int)
R
user_ratings_mean = np.mean(R, axis = 1)
user_ratings_mean

array([0.05990286, 0.44522396, 0.06206152, ..., 0.03184026, 0.15002698,
       0.35429034])

In [21]:
user_ratings_mean.reshape(-1, 1) #-1 is for unknown dimension


array([[0.05990286],
       [0.44522396],
       [0.06206152],
       ...,
       [0.03184026],
       [0.15002698],
       [0.35429034]])

In [22]:
R_demeaned = R - user_ratings_mean.reshape(-1, 1)
R

array([[5, 0, 0, ..., 0, 0, 0],
       [5, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [4, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [0]:
from scipy.sparse.linalg import svds
U, sigma, Vt = svds(R_demeaned, k = 50)

In [24]:
U.shape

(6040, 50)

In [0]:
sigma = np.diag(sigma)

In [26]:
all_user_predicted_ratings = np.dot(np.dot(U, sigma), Vt) + user_ratings_mean.reshape(-1, 1)
all_user_predicted_ratings

array([[ 4.28886061e+00, -1.95949954e-01,  5.97905159e-02, ...,
         3.69448331e-02,  6.05339706e-02,  5.07522018e-02],
       [ 4.51691241e+00,  9.42799641e-01, -1.85102236e-01, ...,
        -1.14662683e-01, -1.53838225e-01, -2.73472961e-01],
       [-7.85461022e-02,  9.07656597e-01, -1.24355693e-02, ...,
         2.40143123e-02, -1.50433388e-03, -2.77038221e-02],
       ...,
       [ 2.51096600e+00, -7.73346045e-03, -9.30083673e-02, ...,
         2.92685658e-02, -1.09956651e-02, -2.10282212e-01],
       [ 1.96157517e+00, -3.36833956e-01,  1.24358241e-02, ...,
         1.70794645e-01,  5.40658314e-02, -1.75652918e-01],
       [ 1.32156042e-01,  2.83102525e+00,  9.24648755e-01, ...,
        -3.50771301e-02,  5.57506501e-01,  4.92852217e-01]])

In [35]:
preds_df = pd.DataFrame(all_user_predicted_ratings, columns = R_df.columns)
preds_df.head(10)
#preds_df.shape

MovieID         1        10       100  ...       997       998       999
0        4.288861 -0.195950  0.059791  ...  0.036945  0.060534  0.050752
1        4.516912  0.942800 -0.185102  ... -0.114663 -0.153838 -0.273473
2       -0.078546  0.907657 -0.012436  ...  0.024014 -0.001504 -0.027704
3        3.800371  0.528449 -0.124235  ... -0.029600  0.087014 -0.181658
4        3.058320  0.926521  0.218438  ...  0.350303  0.240005  0.596033
5       -0.613451 -0.417328  0.089704  ... -0.016811  0.033274  0.099657
6        0.081269  0.077387  0.124809  ...  0.004682 -0.004896  0.001197
7        5.415994  3.965716 -0.108522  ... -0.006150  0.038989  0.076044
8        2.602145 -0.202192  0.023928  ... -0.037692  0.091113  0.004181
9        0.547811 -0.003329  0.015921  ...  0.008723  0.012242  0.012070

[10 rows x 3706 columns]

In [0]:
ratings_df.dtypes
ratings_df["MovieID"] = pd.to_numeric(ratings_df["MovieID"])
ratings_df = ratings_df.astype(object)
movies_df=movies_df.astype(object)

In [0]:
def recommend_movies(predictions_df, userID, movies_df, original_ratings_df, num_recommendations=5):
    # Get and sort the user's predictions
    user_row_number = userID - 1 # UserID starts at 1, not 0
    sorted_user_predictions = preds_df.iloc[user_row_number].sort_values(ascending=False) # UserID starts at 1
    
    
    # Get the user's data and merge in the movie information.
    user_data = original_ratings_df[original_ratings_df['UserID'].astype(int)==user_row_number]
    user_full = (user_data.merge(movies_df, how = 'left', left_on = 'MovieID', right_on = 'MovieID').
                     sort_values(['Rating'], ascending=False)
                 )

    print('User {0} has already rated {1} movies.'.format(userID, user_full.shape))
    print('Recommending highest {0} predicted ratings movies not already rated.'.format(num_recommendations))
    
    # Recommend the highest predicted rating movies that the user hasn't seen yet.
    recommendations = (movies_df[~movies_df['MovieID'].isin(user_full['MovieID'])].
         merge(pd.DataFrame(sorted_user_predictions).reset_index(), how = 'left',
               left_on = 'MovieID',
               right_on = 'MovieID').
         rename(columns = {user_row_number: 'Predictions'}).
         sort_values('Predictions', ascending = False).
                       iloc[:num_recommendations, :-1]
                      )

    return user_full, recommendations

In [98]:
already_rated, predictions = recommend_movies(preds_df, 14, movies_df, ratings_df, 5)

User 14 has already rated (108, 6) movies.
Recommending highest 5 predicted ratings movies not already rated.


In [99]:
already_rated.head()

UserID  ...                             Genres
27     13  ...             Action|Adventure|Drama
79     13  ...                      Adventure|War
20     13  ...                     Drama|Thriller
12     13  ...  Action|Adventure|Drama|Sci-Fi|War
21     13  ...             Action|Sci-Fi|Thriller

[5 rows x 6 columns]

In [100]:
predictions

MovieID                               Title                       Genres
0       1                    Toy Story (1995)  Animation|Children's|Comedy
1       3             Grumpier Old Men (1995)               Comedy|Romance
2       4            Waiting to Exhale (1995)                 Comedy|Drama
3       5  Father of the Bride Part II (1995)                       Comedy
4       6                         Heat (1995)        Action|Crime|Thriller